# Generated by Django 5.2.13 on 2026-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
