# Generated by Django 5.2.13 on 2026-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='choice_status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
